"""Sprint 12 scale profiling — real measurements against the benchmark dataset.

Measures the two concrete points flagged in the Sprint 12 roadmap item, plus the
deterministic (non-LLM) pipeline stages, against real data generated by
`generate_benchmark.py`. Deliberately does NOT call any LLM: this environment has no
`OPENAI_API_KEY` configured, and Sprint 12's own instructions ask to be cost-conscious
about real LLM calls against a 200k-row dataset. Instead:

  - Point 1 (extractor.py::_extract_schema prompt size) is measured directly — it's a
    pure string-size question, no LLM call needed to measure it.
  - Point 2 (sandbox.py fixed timeout) is measured by running representative code
    through `execute_in_sandbox()` directly — the same code SHAPE the Transformer/
    Analyst/Science prompts ask the LLM to produce (clean+filter, groupby+agg+plot,
    sklearn model fit), authored here instead of LLM-generated. This measures the
    real sandbox execution/timeout mechanics without spending any LLM budget.
  - Extractor (I/O) and Quality (deterministic checks, no LLM) are run for real via
    their actual production functions.

Usage:
    python case_study/data/profile_scale.py --csv case_study/data/benchmark_200k_300c.csv
"""

from __future__ import annotations

import argparse
import json
import time
import tracemalloc
from dataclasses import dataclass, field
from typing import Any

import pandas as pd

from ai_etl.agents.pipeline.extractor import _extract_schema
from ai_etl.agents.pipeline.quality import quality_node
from ai_etl.core.sandbox import execute_in_sandbox
from ai_etl.sources.csv_source import load_csv


@dataclass
class Measurement:
    name: str
    seconds: float
    peak_mb: float
    extra: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "seconds": round(self.seconds, 3),
            "peak_mb": round(self.peak_mb, 1),
            **self.extra,
        }


def _measure(name: str, fn: Any, **extra: Any) -> tuple[Any, Measurement]:
    tracemalloc.start()
    start = time.monotonic()
    result = fn()
    elapsed = time.monotonic() - start
    _current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    return result, Measurement(name=name, seconds=elapsed, peak_mb=peak / 1e6, extra=extra)


# ---------------------------------------------------------------------------
# Point 1: extractor schema size (no LLM needed — pure measurement)
# ---------------------------------------------------------------------------


def _naive_schema(df: pd.DataFrame) -> dict[str, Any]:
    """Reproduces the PRE-ADR-012 `_extract_schema()` exactly (git history:
    `agents/extractor.py` before this sprint's fix) — `_extract_schema` itself has
    already been fixed as part of this same PR, so calling the real function no
    longer represents the "before" state. This is measured here, standalone, purely
    to get an honest before/after comparison against the real fixed function below.
    """
    return {
        "columns": df.columns.tolist(),
        "dtypes": {col: str(dtype) for col, dtype in df.dtypes.items()},
        "shape": list(df.shape),
        "sample": df.head(3).to_dict(orient="records"),
        "null_counts": df.isnull().sum().to_dict(),
    }


def profile_schema_size(df: pd.DataFrame, n_sources: int) -> Measurement:
    """Compares the pre-fix naive schema (unbounded raw sample) against the real,
    already-fixed `_extract_schema()` this PR ships (MAX_SAMPLE_COLUMNS-capped)."""
    naive_schema = _naive_schema(df)
    fixed_schema = _extract_schema(df)

    current_json = json.dumps(naive_schema, default=str, ensure_ascii=False)
    compact_json = json.dumps(fixed_schema, default=str, ensure_ascii=False)

    # Rough token estimate: OpenAI's tokenizer averages ~4 chars/token for this
    # kind of JSON-ish text (no tiktoken dependency in this project — see
    # pyproject.toml — so this is a documented approximation, not padded further).
    current_tokens_est = len(current_json) / 4
    compact_tokens_est = len(compact_json) / 4

    return Measurement(
        name="extractor_schema_size",
        seconds=0.0,
        peak_mb=0.0,
        extra={
            "n_cols": len(df.columns),
            "current_schema_chars": len(current_json),
            "current_schema_tokens_est": round(current_tokens_est),
            "compact_schema_chars": len(compact_json),
            "compact_schema_tokens_est": round(compact_tokens_est),
            "reduction_pct": round(100 * (1 - len(compact_json) / len(current_json)), 1),
            "multi_source_current_tokens_est_x3": round(current_tokens_est * n_sources),
            "multi_source_compact_tokens_est_x3": round(compact_tokens_est * n_sources),
        },
    )


# ---------------------------------------------------------------------------
# Point 2: sandbox timeout vs. real execution time at scale
# ---------------------------------------------------------------------------

_TRANSFORMER_CODE = """
def transform(dfs):
    df = dfs["df"].copy()
    numeric_cols = [c for c in df.columns if c.startswith("metric_")]
    for c in numeric_cols:
        df[c] = df[c].fillna(df[c].median())
    df = df.drop_duplicates()
    df = df[df["row_id"].notnull()]
    return df
"""

_ANALYST_CODE = """
numeric_cols = [c for c in df.columns if c.startswith("metric_")]
cat_cols = [c for c in df.columns if c.startswith("category_")]
agg_col = cat_cols[0]
value_col = numeric_cols[0]
gold_df = df.groupby(agg_col, dropna=False)[value_col].agg(["mean", "sum", "count"]).reset_index()
fig = px.bar(gold_df, x=agg_col, y="mean")
narrative = f"Aggregated {value_col} by {agg_col} across {len(df)} rows."
"""

_SCIENCE_CODE = """
numeric_cols = [c for c in df.columns if c.startswith("metric_")][:10]
work = df[numeric_cols].fillna(df[numeric_cols].median())
target_col = numeric_cols[0]
feature_cols = numeric_cols[1:]
X = work[feature_cols]
y = work[target_col]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=50, max_depth=8, random_state=42, n_jobs=1)
model.fit(X_train, y_train)
preds = model.predict(X_test)
predictions_df = X_test.copy()
predictions_df["actual"] = y_test.values
predictions_df["predicted"] = preds
fig = px.scatter(predictions_df, x="actual", y="predicted")
narrative = f"RandomForest trained on {len(X_train)} rows, {len(feature_cols)} features."
model_info = {"model": "RandomForestRegressor", "r2": float(r2_score(y_test, preds))}
"""


def profile_sandbox_transformer(df: pd.DataFrame, timeout_seconds: int) -> Measurement:
    start = time.monotonic()
    result = execute_in_sandbox(
        _TRANSFORMER_CODE, {"df": df.copy()}, mode="function", timeout_seconds=timeout_seconds
    )
    elapsed = time.monotonic() - start
    return Measurement(
        name="sandbox_transformer_style",
        seconds=elapsed,
        peak_mb=0.0,
        extra={"n_rows": len(df), "timed_out": result["timed_out"], "error": result["error"]},
    )


def profile_sandbox_analyst(df: pd.DataFrame, timeout_seconds: int) -> Measurement:
    start = time.monotonic()
    result = execute_in_sandbox(
        _ANALYST_CODE,
        {"df": df.copy()},
        mode="script",
        result_vars=["gold_df", "fig", "narrative"],
        extra_modules={"px": "plotly.express", "go": "plotly.graph_objects"},
        timeout_seconds=timeout_seconds,
    )
    elapsed = time.monotonic() - start
    return Measurement(
        name="sandbox_analyst_style",
        seconds=elapsed,
        peak_mb=0.0,
        extra={"n_rows": len(df), "timed_out": result["timed_out"], "error": result["error"]},
    )


def profile_sandbox_science(df: pd.DataFrame, timeout_seconds: int) -> Measurement:
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.metrics import r2_score
    from sklearn.model_selection import train_test_split

    extra_globals = {
        "RandomForestRegressor": RandomForestRegressor,
        "train_test_split": train_test_split,
        "r2_score": r2_score,
    }
    start = time.monotonic()
    result = execute_in_sandbox(
        _SCIENCE_CODE,
        {"df": df.copy()},
        mode="script",
        result_vars=["predictions_df", "fig", "narrative", "model_info"],
        extra_globals=extra_globals,
        extra_modules={"px": "plotly.express"},
        timeout_seconds=timeout_seconds,
    )
    elapsed = time.monotonic() - start
    return Measurement(
        name="sandbox_science_style",
        seconds=elapsed,
        peak_mb=0.0,
        extra={"n_rows": len(df), "timed_out": result["timed_out"], "error": result["error"]},
    )


def profile_quality(df: pd.DataFrame, source_schemas: dict[str, Any]) -> Measurement:
    state = {
        "run_id": "profile-scale-run",
        "transformed_data": df,
        "source_schemas": source_schemas,
        "audit_log": [],
        "error": None,
        "status": "running",
    }
    _result, m = _measure("quality_node", lambda: quality_node(state))  # type: ignore[arg-type]
    m.extra["n_rows"] = len(df)
    return m


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=str, default="case_study/data/benchmark_200k_300c.csv")
    parser.add_argument("--report", type=str, default="")
    args = parser.parse_args()

    measurements: list[Measurement] = []

    df, m_extract = _measure("extractor_load_csv", lambda: load_csv(args.csv))
    measurements.append(m_extract)
    m_extract.extra["n_rows"] = len(df)
    m_extract.extra["n_cols"] = len(df.columns)

    m_schema = profile_schema_size(df, n_sources=3)
    measurements.append(m_schema)

    source_schemas = {"benchmark": _extract_schema(df)}

    measurements.append(profile_sandbox_transformer(df, timeout_seconds=30))
    measurements.append(profile_sandbox_analyst(df, timeout_seconds=15))
    measurements.append(profile_sandbox_science(df, timeout_seconds=20))
    measurements.append(profile_quality(df, source_schemas))

    report = {"csv": args.csv, "measurements": [m.as_dict() for m in measurements]}
    text = json.dumps(report, indent=2, ensure_ascii=False)
    print(text)
    if args.report:
        with open(args.report, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
